### ISSUE TITLE
feedback_required what it's mean?? how to solve this error

### ISSUE THREAD

**Issue by sondangpangaribuan** [liamcottle/Instagram-SDK-PHP#39]
Hi... 
I get this error what it's mean how to solves this..
Thank you..

exception 'Instagram\API\Framework\InstagramException' with message 'Failed to followUser: [fail] feedback_required' in /home/belisip/public_html/helper/vendor/liamcottle/instagram-sdk-php/src/Instagram.php:1142 Stack trace: #0 /home/belisip/public_html/controller/integrations.php(398): Instagram\Instagram->followUser(Object(Instagram\API\Response\Model\User)) #1 /home/belisip/public_html/controller/integrations.php(104): integrations->igFollowUser(10, 'rina.zahara3', '{"loggedInUser"...') #2 [internal function]: integrations->runCron() #3 /home/belisip/public_html/core/init.php(168): call_user_func_array(Array, Array) #4 /home/belisip/public_html/index.php(70): include('/home/belisip/p...') #5 {main}gagal igFollowUser
exception 'Instagram\API\Framework\InstagramException' with message 'Failed to followUser: [fail] feedback_required' in /home/belisip/public_html/helper/vendor/liamcottle/instagram-sdk-php/src/Instagram.php:1142 Stack trace: #0 /home/belisip/public_html/controller/integrations.php(398): Instagram\Instagram->followUser(Object(Instagram\API\Response\Model\User)) #1 /home/belisip/public_html/controller/integrations.php(106): integrations->igFollowUser(10, 'rina.zahara3', '{"loggedInUser"...') #2 [internal function]: integrations->runCron() #3 /home/belisip/public_html/core/init.php(168): call_user_func_array(Array, Array) #4 /home/belisip/public_html/index.php(70): include('/home/belisip/p...') #5 {main}gagal igFollowUser

**Comment by pyrkamarcin** [comment]
You get ban. Too much requests into Instagram API.

**Comment by sondangpangaribuan** [comment]
Hi pyrkamarcin This permanently blocked or a while ?? Nothing to solve this??

**Comment by pyrkamarcin** [comment]
Typicaly is 24h. I dont any methods to solve this ban.

niedz., 12.03.2017, 10:10 użytkownik sondangpangaribuan <
notifications@github.com> napisał:

**Comment by pr0ph0z** [comment]
well, i think it's because u r send too much requests. try to use delay.

**Comment by kur1977** [comment]
I get this error only when use commentOnMedia method.
postPhoto, likeMedia are both work fine.
But commentOnMedia returns me an error 

Failed to commentOnMedia: [fail] feedback_required
